#include "StaticData.h"
#include "port/ShipUtils.h"

#include "prop.h"

namespace Rando {

namespace StaticData {
std::array<std::string, RC_MAX> CheckNames = std::array<std::string, RC_MAX>();

#define RC(id, type, world, actor, cId, x, y, z)      \
    {                                                 \
        id, {                                         \
            id, #id, type, world, actor, cId, x, y, z \
        }                                             \
    }

// clang-format off
std::map<RandoCheckId, RandoStaticCheck> Checks = {
    RC(RC_UNKNOWN,                                      RCTYPE_UNKNOWN,         LEVEL_D_CUTSCENE,           ACTOR_1_UNKNOWN,            NULL,                                           0, 0, 0),
    RC(RC_CC_EMPTY_HONEYCOMB_ABOVEWATER,                RCTYPE_EMPTY_HONEYCOMB, LEVEL_3_CLANKERS_CAVERN,    ACTOR_47_EMPTY_HONEYCOMB,   HONEYCOMB_6_CC_ABOVE_WATER,                     7886, 4272, 1969),
    RC(RC_CC_EMPTY_HONEYCOMB_UNDERWATER,                RCTYPE_EMPTY_HONEYCOMB, LEVEL_3_CLANKERS_CAVERN,    ACTOR_47_EMPTY_HONEYCOMB,   HONEYCOMB_5_CC_UNDERWATER,                      3718, 3311, 2519),
    RC(RC_CC_JIGGY_BOLT,                                RCTYPE_JIGGY,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_46_JIGGY,             JIGGY_18_CC_BOLT,                               90, 5962, -12),
    RC(RC_CC_JIGGY_CLANKER_RAISED,                      RCTYPE_JIGGY,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_46_JIGGY,             JIGGY_17_CC_CLANKER_RAISED,                     0, 0, 0),
    RC(RC_CC_JIGGY_FAST_SAWBLADES,                      RCTYPE_JIGGY,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_46_JIGGY,             JIGGY_1E_CC_FAST_SAWBLADES,                     0, -340, -1604),
    RC(RC_CC_JIGGY_JINJO,                               RCTYPE_JIGGY,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_46_JIGGY,             JIGGY_15_CC_JINJO,                              0, 0, 0),
    RC(RC_CC_JIGGY_LONG_PIPE,                           RCTYPE_JIGGY,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_46_JIGGY,             JIGGY_1A_CC_LONG_PIPE,                          4629, 2151, 3082),
    RC(RC_CC_JIGGY_RINGS,                               RCTYPE_JIGGY,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_46_JIGGY,             JIGGY_1C_CC_RINGS,                              0, 0, 0),
    RC(RC_CC_JIGGY_SLOW_SAWBLADES,                      RCTYPE_JIGGY,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_46_JIGGY,             JIGGY_1D_CC_SLOW_SAWBLADES,                     10, -391, -2185),
    RC(RC_CC_JIGGY_TAIL,                                RCTYPE_JIGGY,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_46_JIGGY,             JIGGY_19_CC_TAIL,                               10061, 5112, 3),
    RC(RC_CC_JIGGY_TOOTH,                               RCTYPE_JIGGY,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_46_JIGGY,             JIGGY_1B_CC_TOOTH,                              0, 0, 0),
    RC(RC_CC_JIGGY_SNIPPETS,                            RCTYPE_JIGGY,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_46_JIGGY,             JIGGY_16_CC_SNIPPETS,                           0, 0, 0),
    RC(RC_CC_JINJO_BLUE,                                RCTYPE_JINJO,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_60_JINJO_BLUE,        NULL,                                           -4726, 5337, -110),
    RC(RC_CC_JINJO_GREEN,                               RCTYPE_JINJO,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_62_JINJO_GREEN,       NULL,                                           6138, 5087, 2637),
    RC(RC_CC_JINJO_ORANGE,                              RCTYPE_JINJO,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_5F_JINJO_ORANGE,      NULL,                                           4326, 2146, -4080),
    RC(RC_CC_JINJO_PINK,                                RCTYPE_JINJO,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_61_JINJO_PINK,        NULL,                                           3644, -474, 48),
    RC(RC_CC_JINJO_YELLOW,                              RCTYPE_JINJO,           LEVEL_3_CLANKERS_CAVERN,    ACTOR_5E_JINJO_YELLOW,      NULL,                                           5017, -3085, -13),
    RC(RC_CC_MOLEHILL_WONDERWING,                       RCTYPE_MOLEHILL,        LEVEL_3_CLANKERS_CAVERN,    ACTOR_12C_MOLEHILL,         ABILITY_12_WONDERWING,                          -259, -500, 1413),
    RC(RC_CC_MUMBO_TOKEN_CHOMPA_BEHIND_CLANKERS_TAIL,   RCTYPE_MUMBO_TOKEN,     LEVEL_3_CLANKERS_CAVERN,    ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_10_CC_CHOMPA_BEHIND_CLANKERS_TAIL,   9823, 4225, -19),
    RC(RC_CC_MUMBO_TOKEN_ABOVE_LEVEL_ENTRANCE,          RCTYPE_MUMBO_TOKEN,     LEVEL_3_CLANKERS_CAVERN,    ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_11_CC_ABOVE_LEVEL_ENTRANCE,          -9694, 5272, 1607),
    RC(RC_CC_MUMBO_TOKEN_TUNNEL_RIGHT_OF_CLANKER,       RCTYPE_MUMBO_TOKEN,     LEVEL_3_CLANKERS_CAVERN,    ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_12_CC_TUNNEL_RIGHT_OF_CLANKER,       870, 2146, -3148),
    RC(RC_CC_MUMBO_TOKEN_ALCOVE_WITH_OPEN_GRATE,        RCTYPE_MUMBO_TOKEN,     LEVEL_3_CLANKERS_CAVERN,    ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_13_CC_ALCOVE_WITH_OPEN_GRATE,        2028, 5456, 2344),
    RC(RC_CC_MUMBO_TOKEN_CLANKERS_LEFT_TOOTH,           RCTYPE_MUMBO_TOKEN,     LEVEL_3_CLANKERS_CAVERN,    ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_14_CC_CLANKERS_LEFT_TOOTH,           532, 1424, 6632),
    RC(RC_CC_NOTE_ABOVE_BOLT_1,                         RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           2036, 5693, -15),
    RC(RC_CC_NOTE_ABOVE_BOLT_2,                         RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           1533, 5693, 381),
    RC(RC_CC_NOTE_ABOVE_BOLT_3,                         RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           1043, 5693, 377),
    RC(RC_CC_NOTE_ABOVE_BOLT_4,                         RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           939, 5693, -17),
    RC(RC_CC_NOTE_CLIMBABLE_PIPE_1,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3013, 4437, 2477),
    RC(RC_CC_NOTE_CLIMBABLE_PIPE_2,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3013, 4827, 2477),
    RC(RC_CC_NOTE_CLIMBABLE_PIPE_3,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3013, 5117, 2477),
    RC(RC_CC_NOTE_CLIMBABLE_PIPE_4,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3013, 5407, 2477),
    RC(RC_CC_NOTE_ENTRANCE_TUNNEL_1,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -2580, 2841, 0),
    RC(RC_CC_NOTE_ENTRANCE_TUNNEL_2,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -2030, 2466, 0),
    RC(RC_CC_NOTE_ENTRANCE_TUNNEL_3,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1480, 2461, 0),
    RC(RC_CC_NOTE_ENTRANCE_TUNNEL_4,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -930, 2437, 0),
    RC(RC_CC_NOTE_ENTRANCE_TUNNEL_5,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -380, 2236, 0),
    RC(RC_CC_NOTE_ENTRANCE_TUNNEL_6,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           170, 2155, 0),
    RC(RC_CC_NOTE_FAST_SAWBLADES_1,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, -500, 1695),
    RC(RC_CC_NOTE_FAST_SAWBLADES_2,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, -500, 1130),
    RC(RC_CC_NOTE_FAST_SAWBLADES_3,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, -500, 555),
    RC(RC_CC_NOTE_FAST_SAWBLADES_4,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, -500, -20),
    RC(RC_CC_NOTE_FAST_SAWBLADES_5,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, -500, -600),
    RC(RC_CC_NOTE_FAST_SAWBLADES_6,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, -500, -1335),
    RC(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_1,              RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, 1002, 5174),
    RC(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_2,              RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           684, 999, 5391),
    RC(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_3,              RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           780, 1004, 6071),
    RC(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_4,              RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           566, 1007, 6712),
    RC(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_5,              RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, 1008, 7036),
    RC(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_6,              RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -566, 1015, 6712),
    RC(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_7,              RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -792, 1005, 6071),
    RC(RC_CC_NOTE_INSIDE_CLANKERS_MOUTH_8,              RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -685, 990, 5391),
    RC(RC_CC_NOTE_LOWER_GILLS_TUNNEL_1,                 RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -998, -387, 0),
    RC(RC_CC_NOTE_LOWER_GILLS_TUNNEL_2,                 RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1399, -539, -10),
    RC(RC_CC_NOTE_LOWER_GILLS_TUNNEL_3,                 RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1801, -493, -10),
    RC(RC_CC_NOTE_LOWER_GILLS_TUNNEL_4,                 RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -2199, -351, -10),
    RC(RC_CC_NOTE_LOWER_GILLS_TUNNEL_5,                 RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -2601, -8, -10),
    RC(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_1,                RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -7636, 5162, -1164),
    RC(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_2,                RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -8284, 5243, -911),
    RC(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_3,                RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -8573, 5244, -353),
    RC(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_4,                RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -9112, 5243, -182),
    RC(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_5,                RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -7910, 5212, 804),
    RC(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_6,                RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -7038, 5212, 754),
    RC(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_7,                RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -6634, 5212, 238),
    RC(RC_CC_NOTE_NEAR_LEVEL_ENTRANCE_8,                RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -6065, 5211, 313),
    RC(RC_CC_NOTE_NEAR_PINK_JINJO_1,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           1600, 953, 20),
    RC(RC_CC_NOTE_NEAR_PINK_JINJO_2,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           1999, 1241, 45),
    RC(RC_CC_NOTE_NEAR_PINK_JINJO_3,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           2399, 1258, 45),
    RC(RC_CC_NOTE_NEAR_SNIPPETS_1,                      RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           13028, 3362, -761),
    RC(RC_CC_NOTE_NEAR_SNIPPETS_2,                      RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           13540, 3362, -973),
    RC(RC_CC_NOTE_NEAR_SNIPPETS_3,                      RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           14096, 3362, -969),
    RC(RC_CC_NOTE_NEAR_SNIPPETS_4,                      RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           14602, 3362, -732),
    RC(RC_CC_NOTE_NEAR_SNIPPETS_5,                      RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           14590, 3362, 702),
    RC(RC_CC_NOTE_NEAR_SNIPPETS_6,                      RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           14105, 3361, 929),
    RC(RC_CC_NOTE_NEAR_SNIPPETS_7,                      RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           13538, 3362, 931),
    RC(RC_CC_NOTE_NEAR_SNIPPETS_8,                      RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           13018, 3362, 713),
    RC(RC_CC_NOTE_NEAR_TAIL_1,                          RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           8755, 4225, -1418),
    RC(RC_CC_NOTE_NEAR_TAIL_2,                          RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           8756, 4225, 1278),
    RC(RC_CC_NOTE_NEAR_TAIL_3,                          RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           9091, 4225, 1104),
    RC(RC_CC_NOTE_NEAR_TAIL_4,                          RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           9449, 4225, 923),
    RC(RC_CC_NOTE_NEAR_TAIL_5,                          RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           9636, 4225, 630),
    RC(RC_CC_NOTE_NEAR_TAIL_6,                          RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           9818, 4225, 339),
    RC(RC_CC_NOTE_NEAR_TAIL_7,                          RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           9818, 4225, -377),
    RC(RC_CC_NOTE_NEAR_TAIL_8,                          RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           9636, 4225, -679),
    RC(RC_CC_NOTE_NEAR_TAIL_9,                          RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           9438, 4225, -978),
    RC(RC_CC_NOTE_NEAR_TAIL_10,                         RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           9091, 4225, -1207),
    RC(RC_CC_NOTE_PIPE_NEAR_SHOCK_PAD_1,                RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6582, 5284, 2536),
    RC(RC_CC_NOTE_PIPE_NEAR_SHOCK_PAD_2,                RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6785, 5121, 2454),
    RC(RC_CC_NOTE_PIPE_NEAR_SHOCK_PAD_3,                RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6989, 4958, 2388),
    RC(RC_CC_NOTE_PIPE_NEAR_SHOCK_PAD_4,                RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           7194, 4787, 2321),
    RC(RC_CC_NOTE_PIPE_NEAR_SHOCK_PAD_5,                RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           7401, 4611, 2247),
    RC(RC_CC_NOTE_SLOW_SAWBLADES_1,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, -425, 1610),
    RC(RC_CC_NOTE_SLOW_SAWBLADES_2,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, -425, 1010),
    RC(RC_CC_NOTE_SLOW_SAWBLADES_3,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, -425, 410),
    RC(RC_CC_NOTE_SLOW_SAWBLADES_4,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, -425, -190),
    RC(RC_CC_NOTE_SLOW_SAWBLADES_5,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, -425, -790),
    RC(RC_CC_NOTE_SLOW_SAWBLADES_6,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, -425, -1390),
    RC(RC_CC_NOTE_TOP_OF_CLANKER_1,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3200, 4243, 0),
    RC(RC_CC_NOTE_TOP_OF_CLANKER_2,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3500, 4269, 2),
    RC(RC_CC_NOTE_TOP_OF_CLANKER_3,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3800, 4281, 0),
    RC(RC_CC_NOTE_TOP_OF_CLANKER_4,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           4100, 4293, 0),
    RC(RC_CC_NOTE_TOP_OF_CLANKER_5,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5300, 4209, 0),
    RC(RC_CC_NOTE_TOP_OF_CLANKER_6,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5600, 4161, 0),
    RC(RC_CC_NOTE_TOP_OF_CLANKER_7,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5899, 4106, 0),
    RC(RC_CC_NOTE_TOP_OF_CLANKER_8,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6200, 4072, 0),
    RC(RC_CC_NOTE_TOP_OF_CLANKER_9,                     RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6500, 4047, 0),
    RC(RC_CC_NOTE_TOP_OF_CLANKER_10,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6800, 4063, 0),
    RC(RC_CC_NOTE_UNDERWATER_LOCK_1,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6361, -3085, -908),
    RC(RC_CC_NOTE_UNDERWATER_LOCK_2,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6716, -3085, -18),
    RC(RC_CC_NOTE_UNDERWATER_LOCK_3,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6350, -3085, 866),
    RC(RC_CC_NOTE_UNDERWATER_LOCK_4,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5468, -3085, 1225),
    RC(RC_CC_NOTE_UNDERWATER_LOCK_5,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           4583, -3085, 865),
    RC(RC_CC_NOTE_UNDERWATER_LOCK_6,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           4220, -3085, -19),
    RC(RC_CC_NOTE_UNDERWATER_LOCK_7,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           4584, -3085, -906),
    RC(RC_CC_NOTE_UNDERWATER_LOCK_8,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5469, -3085, -1273),
    RC(RC_CC_NOTE_UNDERWATER_PIPE_1,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3866, 1198, 2618),
    RC(RC_CC_NOTE_UNDERWATER_PIPE_2,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           4427, 1188, 2637),
    RC(RC_CC_NOTE_UNDERWATER_PIPE_3,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           4961, 1184, 2649),
    RC(RC_CC_NOTE_UNDERWATER_PIPE_4,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5417, 1184, 2626),
    RC(RC_CC_NOTE_UNDERWATER_PIPE_5,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5881, 1184, 2600),
    RC(RC_CC_NOTE_UNDERWATER_PIPE_6,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6342, 1184, 2485),
    RC(RC_CC_NOTE_UNDERWATER_PIPE_7,                    RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6804, 1184, 2361),
    RC(RC_CC_NOTE_YELLOW_GRATE_1,                       RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           2240, 5262, -2473),
    RC(RC_CC_NOTE_YELLOW_GRATE_2,                       RCTYPE_MUSIC_NOTE,      LEVEL_3_CLANKERS_CAVERN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5270, 5261, -2937),
    RC(RC_GV_EMPTY_HONEYCOMB_CACTUS,                    RCTYPE_EMPTY_HONEYCOMB, LEVEL_7_GOBIS_VALLEY,       ACTOR_47_EMPTY_HONEYCOMB,   HONEYCOMB_B_GV_CACTUS,                          2911, 3292, -3307),
    RC(RC_GV_EMPTY_HONEYCOMB_GOBI,                      RCTYPE_EMPTY_HONEYCOMB, LEVEL_7_GOBIS_VALLEY,       ACTOR_47_EMPTY_HONEYCOMB,   HONEYCOMB_C_GV_GOBI_3,                          -6885, 2383, 1335),
    RC(RC_GV_JIGGY_ANCIENT_ONES,                        RCTYPE_JIGGY,           LEVEL_7_GOBIS_VALLEY,       ACTOR_46_JIGGY,             JIGGY_46_GV_ANCIENT_ONES,                       0, 0, 0),
    RC(RC_GV_JIGGY_GOBI_1,                              RCTYPE_JIGGY,           LEVEL_7_GOBIS_VALLEY,       ACTOR_46_JIGGY,             JIGGY_44_GV_GOBI_1,                             0, 0, 0),
    RC(RC_GV_JIGGY_GOBI_2,                              RCTYPE_JIGGY,           LEVEL_7_GOBIS_VALLEY,       ACTOR_46_JIGGY,             JIGGY_45_GV_GOBI_2,                             0, 0, 0),
    RC(RC_GV_JIGGY_GRABBA,                              RCTYPE_JIGGY,           LEVEL_7_GOBIS_VALLEY,       ACTOR_46_JIGGY,             JIGGY_3E_GV_GRABBA,                             -4644, 1875, -4831),
    RC(RC_GV_JIGGY_HISTUP,                              RCTYPE_JIGGY,           LEVEL_7_GOBIS_VALLEY,       ACTOR_46_JIGGY,             JIGGY_43_GV_HISTUP,                             0, 0, 0),
    RC(RC_GV_JIGGY_JINJO,                               RCTYPE_JIGGY,           LEVEL_7_GOBIS_VALLEY,       ACTOR_46_JIGGY,             JIGGY_3D_GV_JINJO,                              0, 0, 0),
    RC(RC_GV_JIGGY_MATCHING_GAME,                       RCTYPE_JIGGY,           LEVEL_7_GOBIS_VALLEY,       ACTOR_46_JIGGY,             JIGGY_40_GV_MATCHING_GAME,                      0, 0, 0),
    RC(RC_GV_JIGGY_MAZE,                                RCTYPE_JIGGY,           LEVEL_7_GOBIS_VALLEY,       ACTOR_46_JIGGY,             JIGGY_41_GV_MAZE,                               -5008, 66, 62),
    RC(RC_GV_JIGGY_SHYINX,                              RCTYPE_JIGGY,           LEVEL_7_GOBIS_VALLEY,       ACTOR_46_JIGGY,             JIGGY_3F_GV_SHYINX,                             -2250, 1970, -49),
    RC(RC_GV_JIGGY_WATER_PYRAMID,                       RCTYPE_JIGGY,           LEVEL_7_GOBIS_VALLEY,       ACTOR_46_JIGGY,             JIGGY_42_GV_WATER_PYRAMID,                      -1, 145, -23),
    RC(RC_GV_JINJO_BLUE,                                RCTYPE_JINJO,           LEVEL_7_GOBIS_VALLEY,       ACTOR_60_JINJO_BLUE,        NULL,                                           3067, 447, 10270),
    RC(RC_GV_JINJO_GREEN,                               RCTYPE_JINJO,           LEVEL_7_GOBIS_VALLEY,       ACTOR_62_JINJO_GREEN,       NULL,                                           2078, 1122, -50),
    RC(RC_GV_JINJO_ORANGE,                              RCTYPE_JINJO,           LEVEL_7_GOBIS_VALLEY,       ACTOR_5F_JINJO_ORANGE,      NULL,                                           58, 535, 1570),
    RC(RC_GV_JINJO_PINK,                                RCTYPE_JINJO,           LEVEL_7_GOBIS_VALLEY,       ACTOR_61_JINJO_PINK,        NULL,                                           -4964, 0, 700),
    RC(RC_GV_JINJO_YELLOW,                              RCTYPE_JINJO,           LEVEL_7_GOBIS_VALLEY,       ACTOR_5E_JINJO_YELLOW,      NULL,                                           4952, 2538, 439),
    RC(RC_GV_MOLEHILL_TURBO_TALON,                      RCTYPE_MOLEHILL,        LEVEL_7_GOBIS_VALLEY,       ACTOR_12C_MOLEHILL,         ABILITY_11_TURBO_TALON,                         -259, -500, 1413),
    RC(RC_GV_MUMBO_TOKEN_BEHIND_SANDYBUTTS_SARCOPHAGUS, RCTYPE_MUMBO_TOKEN,     LEVEL_7_GOBIS_VALLEY,       ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_2F_GV_BEHIND_SANDYBUTTS_SARCOPHAGUS, -5514, 0, 138),
    RC(RC_GV_MUMBO_TOKEN_BOTTOM_OF_MOAT,                RCTYPE_MUMBO_TOKEN,     LEVEL_7_GOBIS_VALLEY,       ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_2B_GV_BOTTOM_OF_MOAT,                91, 535, -860),
    RC(RC_GV_MUMBO_TOKEN_FRONT_OF_STAR_DOOR,            RCTYPE_MUMBO_TOKEN,     LEVEL_7_GOBIS_VALLEY,       ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_2D_GV_FRONT_OF_STAR_DOOR,            -230, 2843, -3091),
    RC(RC_GV_MUMBO_TOKEN_INSIDE_JINXY,                  RCTYPE_MUMBO_TOKEN,     LEVEL_7_GOBIS_VALLEY,       ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_32_GV_INSIDE_JINXY,                  -2550, 0, -51),
    RC(RC_GV_MUMBO_TOKEN_INSIDE_MEMORY_GAME_ROOM,       RCTYPE_MUMBO_TOKEN,     LEVEL_7_GOBIS_VALLEY,       ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_2E_GV_INSIDE_MEMORY_GAME_ROOM,       715, 248, 0),
    RC(RC_GV_MUMBO_TOKEN_INSIDE_WATER_PYRAMID,          RCTYPE_MUMBO_TOKEN,     LEVEL_7_GOBIS_VALLEY,       ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_30_GV_INSIDE_WATER_PYRAMID,          -300, 1439, -1194),
    RC(RC_GV_MUMBO_TOKEN_NEXT_TO_RUBEE,                 RCTYPE_MUMBO_TOKEN,     LEVEL_7_GOBIS_VALLEY,       ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_31_GV_NEXT_TO_RUBEE,                 0, 107, -602),
    RC(RC_GV_MUMBO_TOKEN_SAND_RIGHT_OF_JINXY,           RCTYPE_MUMBO_TOKEN,     LEVEL_7_GOBIS_VALLEY,       ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_2A_GV_SAND_RIGHT_OF_JINXY,           -5386, 1420, 10034),
    RC(RC_GV_MUMBO_TOKEN_TOP_OF_JINXYS_NOSE,            RCTYPE_MUMBO_TOKEN,     LEVEL_7_GOBIS_VALLEY,       ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_29_GV_TOP_OF_JINXYS_NOSE,            -2149, 3340, 5867),
    RC(RC_GV_MUMBO_TOKEN_TOP_OF_WATER_PYRAMID,          RCTYPE_MUMBO_TOKEN,     LEVEL_7_GOBIS_VALLEY,       ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_2C_GV_TOP_OF_WATER_PYRAMID,          64, 3484, 400),
    RC(RC_GV_NOTE_DESERT_DOOR_ALCOVE_1,                 RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -7178, 2372, 1754),
    RC(RC_GV_NOTE_DESERT_DOOR_ALCOVE_2,                 RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -7148, 2371, 1568),
    RC(RC_GV_NOTE_DESERT_DOOR_ALCOVE_3,                 RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -7123, 2371, 1404),
    RC(RC_GV_NOTE_DESERT_DOOR_ALCOVE_4,                 RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -7105, 2371, 1247),
    RC(RC_GV_NOTE_DESERT_DOOR_ALCOVE_5,                 RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -7082, 2372, 1091),
    RC(RC_GV_NOTE_ENTRANCE_1,                           RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           88, 460, 8403),
    RC(RC_GV_NOTE_ENTRANCE_2,                           RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -251, 697, 8089),
    RC(RC_GV_NOTE_ENTRANCE_3,                           RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -584, 894, 7778),
    RC(RC_GV_NOTE_ENTRANCE_4,                           RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -935, 1082, 7449),
    RC(RC_GV_NOTE_ENTRANCE_5,                           RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -1289, 1259, 7119),
    RC(RC_GV_NOTE_MATCH_GAME_PYRAMID_INTERIOR_1,        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -450, 19, -450),
    RC(RC_GV_NOTE_MATCH_GAME_PYRAMID_INTERIOR_2,        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -450, 19, 450),
    RC(RC_GV_NOTE_MATCH_GAME_PYRAMID_INTERIOR_3,        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           450, 19, -450),
    RC(RC_GV_NOTE_MATCH_GAME_PYRAMID_INTERIOR_4,        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           450, 19, 450),
    RC(RC_GV_NOTE_MATCH_GAME_PYRAMID_SIDE_1,            RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           4215, 2452, -715),
    RC(RC_GV_NOTE_MATCH_GAME_PYRAMID_SIDE_2,            RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           4815, 2452, -714),
    RC(RC_GV_NOTE_MATCH_GAME_PYRAMID_STAIRS_1,          RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           2395, 2130, -300),
    RC(RC_GV_NOTE_MATCH_GAME_PYRAMID_STAIRS_2,          RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           3090, 2730, -300),
    RC(RC_GV_NOTE_MATCH_GAME_PYRAMID_STAIRS_3,          RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           3090, 2730, 970),
    RC(RC_GV_NOTE_MATCH_GAME_PYRAMID_STAIRS_4,          RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           2395, 2130, 970),
    RC(RC_GV_NOTE_MATCH_GAME_PYRAMID_TOP_1,             RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           3792, 2656, 325),
    RC(RC_GV_NOTE_MATCH_GAME_PYRAMID_TOP_2,             RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           3930, 2849, 324),
    RC(RC_GV_NOTE_MATCH_GAME_PYRAMID_TOP_3,             RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           4070, 3040, 324),
    RC(RC_GV_NOTE_MATCH_GAME_PYRAMID_TOP_4,             RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           4211, 3233, 324),
    RC(RC_GV_NOTE_MAZE_PYRAMID_INTERIOR_1,              RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -4002, 0, 43),
    RC(RC_GV_NOTE_MAZE_PYRAMID_INTERIOR_2,              RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3504, 0, -190),
    RC(RC_GV_NOTE_MAZE_PYRAMID_INTERIOR_3,              RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -2735, 0, 203),
    RC(RC_GV_NOTE_MAZE_PYRAMID_INTERIOR_4,              RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -1913, 3, 210),
    RC(RC_GV_NOTE_MAZE_PYRAMID_INTERIOR_5,              RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           4729, 0, -45),
    RC(RC_GV_NOTE_MAZE_PYRAMID_INTERIOR_6,              RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           4178, 0, 205),
    RC(RC_GV_NOTE_MAZE_PYRAMID_INTERIOR_7,              RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           5400, 0, 326),
    RC(RC_GV_NOTE_MAZE_PYRAMID_STAIRS_1,                RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -464, 2770, 1610),
    RC(RC_GV_NOTE_MAZE_PYRAMID_STAIRS_2,                RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -464, 2170, 2305),
    RC(RC_GV_NOTE_MAZE_PYRAMID_STAIRS_3,                RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           684, 2770, 1610),
    RC(RC_GV_NOTE_MAZE_PYRAMID_STAIRS_4,                RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           685, 2170, 2305),
    RC(RC_GV_NOTE_MOAT_BOTTOM_1,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -908, 535, -472),
    RC(RC_GV_NOTE_MOAT_BOTTOM_2,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -1182, 535, 457),
    RC(RC_GV_NOTE_MOAT_BOTTOM_3,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -807, 535, 1318),
    RC(RC_GV_NOTE_MOAT_BOTTOM_4,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           928, 535, 1291),
    RC(RC_GV_NOTE_MOAT_BOTTOM_5,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           1234, 535, 411),
    RC(RC_GV_NOTE_MOAT_BOTTOM_6,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           1055, 535, -458),
    RC(RC_GV_NOTE_MOAT_EDGE_1,                          RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -2111, 1830, 1016),
    RC(RC_GV_NOTE_MOAT_EDGE_2,                          RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -2100, 1830, 112),
    RC(RC_GV_NOTE_MOAT_EDGE_3,                          RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -2098, 1830, -785),
    RC(RC_GV_NOTE_MOAT_EDGE_4,                          RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -1455, 1830, -1432),
    RC(RC_GV_NOTE_MOAT_EDGE_5,                          RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -800, 1830, -2068),
    RC(RC_GV_NOTE_MOAT_EDGE_6,                          RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           110, 1830, -2068),
    RC(RC_GV_NOTE_MOAT_EDGE_7,                          RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           1019, 1830, -2068),
    RC(RC_GV_NOTE_MOAT_EDGE_8,                          RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           1671, 1830, -1416),
    RC(RC_GV_NOTE_MOAT_EDGE_9,                          RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           2307, 1837, -770),
    RC(RC_GV_NOTE_NEAR_GRABBA_1,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3017, 1781, -5496),
    RC(RC_GV_NOTE_NEAR_GRABBA_2,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3026, 1781, -5048),
    RC(RC_GV_NOTE_NEAR_GRABBA_3,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3028, 1781, -4591),
    RC(RC_GV_NOTE_NEAR_GRABBA_4,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3037, 1781, -4148),
    RC(RC_GV_NOTE_NEAR_GRABBA_5,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3054, 1781, -3695),
    RC(RC_GV_NOTE_NEAR_GRABBA_6,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3401, 1780, -3430),
    RC(RC_GV_NOTE_NEAR_GRABBA_7,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3752, 1781, -3161),
    RC(RC_GV_NOTE_NEAR_GRABBA_8,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -4116, 1780, -2895),
    RC(RC_GV_NOTE_NEAR_GRABBA_9,                        RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -4541, 1780, -2871),
    RC(RC_GV_NOTE_NEAR_GRABBA_10,                       RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -4958, 1781, -2855),
    RC(RC_GV_NOTE_NEAR_GRABBA_11,                       RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -5385, 1780, -2843),
    RC(RC_GV_NOTE_NEAR_RUBEE_1,                         RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -685, 0, -743),
    RC(RC_GV_NOTE_NEAR_RUBEE_2,                         RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -495, 0, -880),
    RC(RC_GV_NOTE_NEAR_RUBEE_3,                         RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -913, 0, 428),
    RC(RC_GV_NOTE_NEAR_RUBEE_4,                         RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -986, 0, 201),
    RC(RC_GV_NOTE_NEAR_RUBEE_5,                         RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           496, 0, -878),
    RC(RC_GV_NOTE_NEAR_RUBEE_6,                         RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           679, 0, -744),
    RC(RC_GV_NOTE_NEAR_RUBEE_7,                         RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           915, 0, 421),
    RC(RC_GV_NOTE_NEAR_RUBEE_8,                         RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           988, 0, 195),
    RC(RC_GV_NOTE_NEAR_TURBO_TRAINERS_1,                RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           2925, 3426, -6331),
    RC(RC_GV_NOTE_NEAR_TURBO_TRAINERS_2,                RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           3522, 3403, -6008),
    RC(RC_GV_NOTE_SAND_NEAR_SPHYNX_1,                   RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3165, 1378, 7933),
    RC(RC_GV_NOTE_SAND_NEAR_SPHYNX_2,                   RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3720, 1390, 8460),
    RC(RC_GV_NOTE_SAND_NEAR_SPHYNX_3,                   RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -4276, 1402, 8984),
    RC(RC_GV_NOTE_SAND_NEAR_SPHYNX_4,                   RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -4829, 1415, 9510),
    RC(RC_GV_NOTE_SAND_NEAR_SPHYNX_5,                   RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -5713, 1379, 9342),
    RC(RC_GV_NOTE_SAND_NEAR_SPHYNX_6,                   RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -6046, 1329, 8619),
    RC(RC_GV_NOTE_SAND_NEAR_SPHYNX_7,                   RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -6367, 1281, 7928),
    RC(RC_GV_NOTE_SAND_NEAR_SPHYNX_8,                   RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -6724, 1233, 7210),
    RC(RC_GV_NOTE_SPHYNX_FOOT_LEFT_1,                   RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -2776, 1606, 6486),
    RC(RC_GV_NOTE_SPHYNX_FOOT_LEFT_2,                   RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3035, 1663, 6675),
    RC(RC_GV_NOTE_SPHYNX_FOOT_LEFT_3,                   RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3048, 1665, 6316),
    RC(RC_GV_NOTE_SPHYNX_FOOT_RIGHT_1,                  RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -2814, 1605, 5292),
    RC(RC_GV_NOTE_SPHYNX_FOOT_RIGHT_2,                  RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3083, 1666, 5488),
    RC(RC_GV_NOTE_SPHYNX_FOOT_RIGHT_3,                  RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3096, 1664, 5106),
    RC(RC_GV_NOTE_SPHYNX_INTERIOR_1,                    RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3310, 0, -850),
    RC(RC_GV_NOTE_SPHYNX_INTERIOR_2,                    RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -3317, 0, 748),
    RC(RC_GV_NOTE_SPHYNX_INTERIOR_3,                    RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -1195, 1592, -50),
    RC(RC_GV_NOTE_SPHYNX_INTERIOR_4,                    RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           95, 911, -50),
    RC(RC_GV_NOTE_SPHYNX_INTERIOR_5,                    RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           1295, 274, -50),
    RC(RC_GV_NOTE_SPHYNX_INTERIOR_6,                    RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           2249, 0, -829),
    RC(RC_GV_NOTE_SPHYNX_INTERIOR_7,                    RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           2265, 0, 753),
    RC(RC_GV_NOTE_WATER_PYRAMID_INTERIOR_1,             RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -5, 13, -757),
    RC(RC_GV_NOTE_WATER_PYRAMID_INTERIOR_2,             RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -776, 13, -3),
    RC(RC_GV_NOTE_WATER_PYRAMID_INTERIOR_3,             RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -14, 13, 734),
    RC(RC_GV_NOTE_WATER_PYRAMID_INTERIOR_4,             RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           729, 13, -11),
    RC(RC_GV_NOTE_WATER_PYRAMID_TOP_1,                  RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -1168, 3324, -3242),
    RC(RC_GV_NOTE_WATER_PYRAMID_TOP_2,                  RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           1214, 3821, -3576),
    RC(RC_GV_NOTE_WATER_PYRAMID_TOP_3,                  RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -828, 3821, -3580),
    RC(RC_GV_NOTE_WATER_PYRAMID_TOP_4,                  RCTYPE_MUSIC_NOTE,      LEVEL_7_GOBIS_VALLEY,       ACTOR_51_MUSIC_NOTE,        NULL,                                           -489, 4316, -4946),
    RC(RC_MM_EMPTY_HONEYCOMB_HILL,                      RCTYPE_EMPTY_HONEYCOMB, LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_47_EMPTY_HONEYCOMB,   HONEYCOMB_1_MM_HILL,                            985, 484, 1681),
    RC(RC_MM_EMPTY_HONEYCOMB_JUJU,                      RCTYPE_EMPTY_HONEYCOMB, LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_47_EMPTY_HONEYCOMB,   HONEYCOMB_2_MM_JUJU,                            4302, 2900, -1490),
    RC(RC_MM_JIGGY_CHIMPY,                              RCTYPE_JIGGY,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_46_JIGGY,             JIGGY_9_MM_CHIMPY,                              -5599, -20, 5599),
    RC(RC_MM_JIGGY_CONGA,                               RCTYPE_JIGGY,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_46_JIGGY,             JIGGY_A_MM_CONGA,                               -3758, -172, 5028),
    RC(RC_MM_JIGGY_HILL,                                RCTYPE_JIGGY,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_46_JIGGY,             JIGGY_07_MM_HILL,                               4335, 1485, 794),
    RC(RC_MM_JIGGY_HUTS,                                RCTYPE_JIGGY,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_46_JIGGY,             JIGGY_5_MM_HUTS,                                0, 0, 0),
    RC(RC_MM_JIGGY_JINJO,                               RCTYPE_JIGGY,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_46_JIGGY,             JIGGY_01_MM_JINJO,                              1702, -41, 2941),
    RC(RC_MM_JIGGY_JUJU,                                RCTYPE_JIGGY,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_46_JIGGY,             JIGGY_4_MM_JUJU,                                4309, 2374, -1487),
    RC(RC_MM_JIGGY_MUMBOS_SKULL,                        RCTYPE_JIGGY,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_46_JIGGY,             JIGGY_03_MM_MUMBOS_SKULL,                       5580, 2756, -2708),
    RC(RC_MM_JIGGY_ORANGE_PADS,                         RCTYPE_JIGGY,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_46_JIGGY,             JIGGY_8_MM_ORANGE_PADS,                         0, 0, 0),
    RC(RC_MM_JIGGY_RUINS,                               RCTYPE_JIGGY,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_46_JIGGY,             JIGGY_06_MM_RUINS,                              -3699, 2438, -2113),
    RC(RC_MM_JIGGY_TICKERS_TOWER,                       RCTYPE_JIGGY,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_46_JIGGY,             JIGGY_02_MM_TICKERS_TOWER,                      373, 4221, -906),
    RC(RC_MM_JINJO_BLUE,                                RCTYPE_JINJO,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_60_JINJO_BLUE,        NULL,                                           1702, -125, 2941),
    RC(RC_MM_JINJO_GREEN,                               RCTYPE_JINJO,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_62_JINJO_GREEN,       NULL,                                           0, 0, 0),
    RC(RC_MM_JINJO_ORANGE,                              RCTYPE_JINJO,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_5F_JINJO_ORANGE,      NULL,                                           -3297, 2755, -1421),
    RC(RC_MM_JINJO_PINK,                                RCTYPE_JINJO,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_61_JINJO_PINK,        NULL,                                           5876, 299, 2369),
    RC(RC_MM_JINJO_YELLOW,                              RCTYPE_JINJO,           LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_5E_JINJO_YELLOW,      NULL,                                           -4060, 1355, 1092),
    RC(RC_MM_MOLEHILL_BEAK_BUSTER,                      RCTYPE_MOLEHILL,        LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_12C_MOLEHILL,         ABILITY_2_BEAK_BUSTER,                          3943, 2155, -3422),
    RC(RC_MM_MOLEHILL_TALON_TROT,                       RCTYPE_MOLEHILL,        LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_12C_MOLEHILL,         ABILITY_10_TALON_TROT,                          -2550, 2255, -1217),
    RC(RC_MM_MOLEHILL_USE_EGGS,                         RCTYPE_MOLEHILL,        LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_12C_MOLEHILL,         ABILITY_6_EGGS,                                 -5926, 200, 6213),
    RC(RC_MM_MUMBO_TOKEN_BEHIND_PINK_JINJO,             RCTYPE_MUMBO_TOKEN,     LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_04_MM_BEHIND_PINK_JINJO,             5855, 0, 2169),
    RC(RC_MM_MUMBO_TOKEN_BEHIND_RUINS,                  RCTYPE_MUMBO_TOKEN,     LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_02_MM_BEHIND_RUINS,                  -4869, 2255, -2506),
    RC(RC_MM_MUMBO_TOKEN_INSIDE_TICKERS_TOWER,          RCTYPE_MUMBO_TOKEN,     LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_05_MM_INSIDE_TICKERS_TOWER,          -343, 345, -518),
    RC(RC_MM_MUMBO_TOKEN_STUMP_NEAR_CONGA,              RCTYPE_MUMBO_TOKEN,     LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_01_MM_STUMP_NEAR_CONGA,              -4431, 475, 6183),
    RC(RC_MM_MUMBO_TOKEN_UNDER_RAMP_TO_MUMBOS_SKULL,    RCTYPE_MUMBO_TOKEN,     LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_2D_MUMBO_TOKEN,       MUMBOTOKEN_03_MM_UNDER_RAMP_TO_MUMBOS_SKULL,    5150, 2168, -2447),
    RC(RC_MM_NOTE_SOUTH_SLOPE_FIRST_PLATFORM_1,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           4867, 297, 1766),
    RC(RC_MM_NOTE_SOUTH_SLOPE_FIRST_PLATFORM_2,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           4782, 298, 1892),
    RC(RC_MM_NOTE_SOUTH_SLOPE_FIRST_PLATFORM_3,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           4971, 299, 1887),
    RC(RC_MM_NOTE_SOUTH_SLOPE_SECOND_PLATFORM_1,        RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6430, 500, 1410),
    RC(RC_MM_NOTE_SOUTH_SLOPE_SECOND_PLATFORM_2,        RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6310, 500, 1536),
    RC(RC_MM_NOTE_SOUTH_SLOPE_SECOND_PLATFORM_3,        RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6546, 500, 1536),
    RC(RC_MM_NOTE_SOUTH_SLOPE_THIRD_PLATFORM_1,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3793, 747, 1471),
    RC(RC_MM_NOTE_SOUTH_SLOPE_THIRD_PLATFORM_2,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3974, 747, 1411),
    RC(RC_MM_NOTE_SOUTH_SLOPE_THIRD_PLATFORM_3,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3928, 747, 1522),
    RC(RC_MM_NOTE_SOUTH_SLOPE_FOURTH_PLATFORM_1,        RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5259, 1184, 656),
    RC(RC_MM_NOTE_SOUTH_SLOPE_FOURTH_PLATFORM_2,        RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5469, 1184, 549),
    RC(RC_MM_NOTE_SOUTH_SLOPE_FOURTH_PLATFORM_3,        RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5412, 1184, 681),
    RC(RC_MM_NOTE_SOUTH_SLOPE_FIFTH_PLATFORM_1,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3202, 1247, 925),
    RC(RC_MM_NOTE_SOUTH_SLOPE_FIFTH_PLATFORM_2,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3126, 1247, 1014),
    RC(RC_MM_NOTE_SOUTH_SLOPE_FIFTH_PLATFORM_3,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3282, 1247, 1003),
    RC(RC_MM_NOTE_SOUTH_SLOPE_SIXTH_PLATFORM_1,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5860, 1547, 62),
    RC(RC_MM_NOTE_SOUTH_SLOPE_SIXTH_PLATFORM_2,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           6098, 1547, 67),
    RC(RC_MM_NOTE_SOUTH_SLOPE_SIXTH_PLATFORM_3,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5990, 1547, 169),
    RC(RC_MM_NOTE_BRIDGE_1,                             RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           2585, -20, 3800),
    RC(RC_MM_NOTE_BRIDGE_2,                             RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           2298, -65, 3800),
    RC(RC_MM_NOTE_BRIDGE_3,                             RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           2012, -90, 3800),
    RC(RC_MM_NOTE_BRIDGE_4,                             RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           1721, -90, 3800),
    RC(RC_MM_NOTE_BRIDGE_5,                             RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           1441, -90, 3800),
    RC(RC_MM_NOTE_BRIDGE_6,                             RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           1149, -62, 3800),
    RC(RC_MM_NOTE_BRIDGE_7,                             RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           854,  -8,  3800),
    RC(RC_MM_NOTE_NORTH_SLOPE_FIRST_PLATFORM_1,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -4497, 393, 2503),
    RC(RC_MM_NOTE_NORTH_SLOPE_FIRST_PLATFORM_2,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -4583, 393, 2600),
    RC(RC_MM_NOTE_NORTH_SLOPE_FIRST_PLATFORM_3,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -4417, 393, 2600),
    RC(RC_MM_NOTE_NORTH_SLOPE_SECOND_PLATFORM_1,        RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -3730, 782, 1838),
    RC(RC_MM_NOTE_NORTH_SLOPE_SECOND_PLATFORM_2,        RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -3776, 782, 1964),
    RC(RC_MM_NOTE_NORTH_SLOPE_SECOND_PLATFORM_3,        RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -3624, 782, 1908),
    RC(RC_MM_NOTE_NORTH_SLOPE_THIRD_PLATFORM_1,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -5185, 837, 1737),
    RC(RC_MM_NOTE_NORTH_SLOPE_THIRD_PLATFORM_2,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -5277, 836, 1850),
    RC(RC_MM_NOTE_NORTH_SLOPE_THIRD_PLATFORM_3,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -5099, 836, 1850),
    RC(RC_MM_NOTE_NORTH_SLOPE_FOURTH_PLATFORM_1,        RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -2962, 1397, 813),
    RC(RC_MM_NOTE_NORTH_SLOPE_FOURTH_PLATFORM_2,        RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -3053, 1397, 905),
    RC(RC_MM_NOTE_NORTH_SLOPE_FOURTH_PLATFORM_3,        RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -2868, 1397, 890),
    RC(RC_MM_NOTE_NORTH_SLOPE_FIFTH_PLATFORM_1,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -5154, 1489, 462),
    RC(RC_MM_NOTE_NORTH_SLOPE_FIFTH_PLATFORM_2,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -5238, 1489, 560),
    RC(RC_MM_NOTE_NORTH_SLOPE_FIFTH_PLATFORM_3,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -5068, 1489, 560),
    RC(RC_MM_NOTE_NORTH_SLOPE_SIXTH_PLATFORM_1,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -4260, 1839, 208),
    RC(RC_MM_NOTE_NORTH_SLOPE_SIXTH_PLATFORM_2,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -4342, 1839, 300),
    RC(RC_MM_NOTE_NORTH_SLOPE_SIXTH_PLATFORM_3,         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -4179, 1839, 300),
    RC(RC_MM_NOTE_NORTH_SLOPE_SEVENTH_PLATFORM_1,       RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -3394, 1910, 171),
    RC(RC_MM_NOTE_NORTH_SLOPE_SEVENTH_PLATFORM_2,       RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -3469, 1910, 263),
    RC(RC_MM_NOTE_NORTH_SLOPE_SEVENTH_PLATFORM_3,       RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -3293, 1910, 247),
    RC(RC_MM_NOTE_NORTH_SLOPE_LOWER_TRAIL_1,            RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1373, 169, 1957),
    RC(RC_MM_NOTE_NORTH_SLOPE_LOWER_TRAIL_2,            RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1431, 346, 1784),
    RC(RC_MM_NOTE_NORTH_SLOPE_LOWER_TRAIL_3,            RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1497, 517, 1621),
    RC(RC_MM_NOTE_NORTH_SLOPE_LOWER_TRAIL_4,            RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1528, 638, 1424),
    RC(RC_MM_NOTE_NORTH_SLOPE_LOWER_TRAIL_5,            RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1523, 742, 1179),
    RC(RC_MM_NOTE_NORTH_SLOPE_LOWER_TRAIL_6,            RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1523, 857, 932),
    RC(RC_MM_NOTE_NORTH_SLOPE_LOWER_TRAIL_7,            RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1518, 964, 706),
    RC(RC_MM_NOTE_NORTH_SLOPE_LOWER_TRAIL_8,            RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1413, 1117, 500),
    RC(RC_MM_NOTE_NORTH_SLOPE_LOWER_TRAIL_9,            RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1284, 1295, 363),
    RC(RC_MM_NOTE_NORTH_SLOPE_HIGHER_TRAIL_1,           RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1094, 1727, -1922),
    RC(RC_MM_NOTE_NORTH_SLOPE_HIGHER_TRAIL_2,           RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1309, 1856, -1941),
    RC(RC_MM_NOTE_NORTH_SLOPE_HIGHER_TRAIL_3,           RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1541, 1987, -1960),
    RC(RC_MM_NOTE_NORTH_SLOPE_HIGHER_TRAIL_4,           RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -1758, 2111, -1974),
    RC(RC_MM_NOTE_RUINS_1,                              RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -3047, 2755, -2669),
    RC(RC_MM_NOTE_RUINS_2,                              RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -3314, 2755, -2802),
    RC(RC_MM_NOTE_RUINS_3,                              RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -3603, 2755, -2923),
    RC(RC_MM_NOTE_RUINS_4,                              RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -3885, 2755, -2901),
    RC(RC_MM_NOTE_RUINS_5,                              RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -4161, 2755, -2858),
    RC(RC_MM_NOTE_RUINS_6,                              RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -4359, 2755, -2682),
    RC(RC_MM_NOTE_RUINS_7,                              RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -4542, 2755, -2495),
    RC(RC_MM_NOTE_RUINS_8,                              RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -4599, 2754, -2261),
    RC(RC_MM_NOTE_RUINS_9,                              RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -4649, 2755, -2009),
    RC(RC_MM_NOTE_RUINS_10,                             RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -4539, 2755, -1746),
    RC(RC_MM_NOTE_RUINS_11,                             RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -4416, 2755, -1509),
    RC(RC_MM_NOTE_RUINS_12,                             RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -4167, 2755, -1383),
    RC(RC_MM_NOTE_RUINS_13,                             RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -3892, 2755, -1284),
    RC(RC_MM_NOTE_RUINS_14,                             RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -3581, 2755, -1359),
    RC(RC_MM_NOTE_UNDERWATER_RIGHT_CAVE_1,              RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           2128, -824, 2181),
    RC(RC_MM_NOTE_UNDERWATER_RIGHT_CAVE_2,              RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           2034, -824, 2158),
    RC(RC_MM_NOTE_UNDERWATER_RIGHT_CAVE_3,              RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           1937, -824, 2136),
    RC(RC_MM_NOTE_UNDERWATER_LEFT_CAVE_1,               RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           1027, -824, 2183),
    RC(RC_MM_NOTE_UNDERWATER_LEFT_CAVE_2,               RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           940, -824, 2223),
    RC(RC_MM_NOTE_UNDERWATER_LEFT_CAVE_3,               RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           850, -824, 2267),
    RC(RC_MM_NOTE_HUT_ROOF_1,                           RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3378, 2439, -2353),
    RC(RC_MM_NOTE_HUT_ROOF_2,                           RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           4137, 2439, -2649),
    RC(RC_MM_NOTE_HUT_ROOF_3,                           RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5319, 2439, -1717),
    RC(RC_MM_NOTE_HUT_ROOF_4,                           RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           5025, 2439, -814),
    RC(RC_MM_NOTE_HUT_ROOF_5,                           RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3847, 2439, -715),
    RC(RC_MM_NOTE_HUT_ROOF_6,                           RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           3255, 2438, -1091),
    RC(RC_MM_NOTE_HUT_BUNDLE_1,                         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, 0, 0),
    RC(RC_MM_NOTE_HUT_BUNDLE_2,                         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, 0, 0),
    RC(RC_MM_NOTE_HUT_BUNDLE_3,                         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, 0, 0),
    RC(RC_MM_NOTE_HUT_BUNDLE_4,                         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, 0, 0),
    RC(RC_MM_NOTE_HUT_BUNDLE_5,                         RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           0, 0, 0),
    RC(RC_MM_NOTE_INSIDE_MUMBOS_SKULL_1,                RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -288, 0, -154),
    RC(RC_MM_NOTE_INSIDE_MUMBOS_SKULL_2,                RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -127, 0, -308),
    RC(RC_MM_NOTE_INSIDE_MUMBOS_SKULL_3,                RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           119, 0, -298),
    RC(RC_MM_NOTE_INSIDE_MUMBOS_SKULL_4,                RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           286, 0, -155),
    RC(RC_MM_NOTE_INSIDE_TICKERS_TOWER_1,               RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -74, 817, 19),
    RC(RC_MM_NOTE_INSIDE_TICKERS_TOWER_2,               RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -3, 817, 52),
    RC(RC_MM_NOTE_INSIDE_TICKERS_TOWER_3,               RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           67, 817, 0),
    RC(RC_MM_NOTE_INSIDE_TICKERS_TOWER_4,               RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           60, 817, -87),
    RC(RC_MM_NOTE_INSIDE_TICKERS_TOWER_5,               RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -10, 817, -125),
    RC(RC_MM_NOTE_INSIDE_TICKERS_TOWER_6,               RCTYPE_MUSIC_NOTE,      LEVEL_1_MUMBOS_MOUNTAIN,    ACTOR_51_MUSIC_NOTE,        NULL,                                           -80, 817, -71),
    RC(RC_SM_EMPTY_HONEYCOMB_COLLIWOBBLE,               RCTYPE_EMPTY_HONEYCOMB, LEVEL_B_SPIRAL_MOUNTAIN,    ACTOR_47_EMPTY_HONEYCOMB,   HONEYCOMB_17_SM_COLLIWOBBLE,                    0, 0, 0),
    RC(RC_SM_EMPTY_HONEYCOMB_QUARRIES,                  RCTYPE_EMPTY_HONEYCOMB, LEVEL_B_SPIRAL_MOUNTAIN,    ACTOR_47_EMPTY_HONEYCOMB,   HONEYCOMB_18_SM_QUARRIES,                       0, 0, 0),
    RC(RC_SM_EMPTY_HONEYCOMB_STUMP,                     RCTYPE_EMPTY_HONEYCOMB, LEVEL_B_SPIRAL_MOUNTAIN,    ACTOR_47_EMPTY_HONEYCOMB,   HONEYCOMB_13_SM_STUMP,                          -1400, 99, 4824),
    RC(RC_SM_EMPTY_HONEYCOMB_TREE,                      RCTYPE_EMPTY_HONEYCOMB, LEVEL_B_SPIRAL_MOUNTAIN,    ACTOR_47_EMPTY_HONEYCOMB,   HONEYCOMB_16_SM_TREE,                           -2752, 1299, 37),
    RC(RC_SM_EMPTY_HONEYCOMB_UNDERWATER,                RCTYPE_EMPTY_HONEYCOMB, LEVEL_B_SPIRAL_MOUNTAIN,    ACTOR_47_EMPTY_HONEYCOMB,   HONEYCOMB_15_SM_UNDERWATER,                     -264, -442, -651),
    RC(RC_SM_EMPTY_HONEYCOMB_WATERFALL,                 RCTYPE_EMPTY_HONEYCOMB, LEVEL_B_SPIRAL_MOUNTAIN,    ACTOR_47_EMPTY_HONEYCOMB,   HONEYCOMB_14_SM_WATERFALL,                      -6725, 1300, -1803),
    RC(RC_SM_MOLEHILL_ATTACK,                           RCTYPE_MOLEHILL,        LEVEL_B_SPIRAL_MOUNTAIN,    ACTOR_12C_MOLEHILL,         ABILITY_4_CLAW_SWIPE,                           4675, 400, 511),
    RC(RC_SM_MOLEHILL_BEAK_BARGE,                       RCTYPE_MOLEHILL,        LEVEL_B_SPIRAL_MOUNTAIN,    ACTOR_12C_MOLEHILL,         ABILITY_0_BARGE,                                3271, -110, -2673),
    RC(RC_SM_MOLEHILL_CAMERA_CONTROL,                   RCTYPE_MOLEHILL,        LEVEL_B_SPIRAL_MOUNTAIN,    ACTOR_12C_MOLEHILL,         ABILITY_3_CAMERA_CONTROL,                       2250, -34, 2774	),
    RC(RC_SM_MOLEHILL_CLIMB,                            RCTYPE_MOLEHILL,        LEVEL_B_SPIRAL_MOUNTAIN,    ACTOR_12C_MOLEHILL,         ABILITY_5_CLIMB,                                -1999, 342, -2545),
    RC(RC_SM_MOLEHILL_DIVE,                             RCTYPE_MOLEHILL,        LEVEL_B_SPIRAL_MOUNTAIN,    ACTOR_12C_MOLEHILL,         ABILITY_F_DIVE,                                 -2336, 302, 973),
    RC(RC_SM_MOLEHILL_JUMP,                             RCTYPE_MOLEHILL,        LEVEL_B_SPIRAL_MOUNTAIN,    ACTOR_12C_MOLEHILL,         ABILITY_A_HOLD_A_JUMP_HIGHER,                   -164, -190, 3313),
};
// clang-format on

RandoCheckId GetCheckByPosition(int32_t posX, int32_t posY, int32_t posZ) {
    for (auto& [randoCheckId, randoStaticCheck] : Checks) {
        if (randoStaticCheck.posX == posX && randoStaticCheck.posY == posY && randoStaticCheck.posZ == posZ) {
            return randoCheckId;
        }
    }

    return RC_UNKNOWN;
}

RandoCheckId GetCheckByJiggyId(int32_t jiggyId) {
    for (auto& [randoCheckId, randoStaticCheck] : Checks) {
        if (randoStaticCheck.randoCheckType != RCTYPE_JIGGY) {
            continue;
        }

        if (randoStaticCheck.collectionId == jiggyId) {
            return randoCheckId;
        }
    }

    return RC_UNKNOWN;
}

RandoCheckId GetJinjoJiggyCheckByLevelId(int16_t levelId) {
    for (auto& [randoCheckId, randoStaticCheck] : Checks) {
        if (randoStaticCheck.randoCheckType != RCTYPE_JIGGY) {
            continue;
        }

        if (randoStaticCheck.collectionId == (10 * levelId) - 9) {
            return randoCheckId;
        }
    }

    return RC_UNKNOWN;
}

} // namespace StaticData
} // namespace Rando