#include "src/port/ShipInit.hpp"
#include "src/port/Rando/Logic/Logic.h"

using namespace Rando::Logic;

// clang-format off
static RegisterShipInitFunc initFunc([]() {
    Regions[RR_BUBBLEGLOOP_SWAMP] = RandoRegion{ .regionName = "Bubblegloop Swamp", .levelId = LEVEL_4_BUBBLEGLOOP_SWAMP,
        .checks = {

        },
        .connections = {
            CONNECTION(RR_BUBBLEGLOOP_SWAMP_INTERIOR_MR_VILES,   CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER)),
            CONNECTION(RR_BUBBLEGLOOP_SWAMP_INTERIOR_MR_VILES,   CAN_USE_TRANSFORMATION(TRANSFORM_5_CROC)),
            CONNECTION(RR_BUBBLEGLOOP_SWAMP_INTERIOR_MUMBOS_SKULL, CAN_USE_TRANSFORMATION(TRANSFORM_5_CROC) || CAN_USE_ABILITY(ABILITY_E_WADING_BOOTS)),
        },
        .events = {
            //NOTE: DOUBLE CHECK IF FLAP FLIP IS REQUIRED.
            EVENT(RA_WITCH_SWITCH_BUBBLEGLOOP_SWAMP, CAN_USE_ABILITY(ABILITY_2_BEAK_BUSTER) && CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP) && CAN_USE_ABILITY(ABILITY_D_SHOCK_JUMP)),
        },
    };
Regions[RR_MUMBOS_MOUNTAIN_INTERIOR_TICKERS_TOWER] = RandoRegion{ .regionName = "Mumbo's Mountain", .levelId = LEVEL_1_MUMBOS_MOUNTAIN,
    .checks = {
        CHECK(RC_MM_MUMBO_TOKEN_INSIDE_TICKERS_TOWER, 		CAN_USE_ABILITY(ABILITY_8_FLAP_FLIP) || CAN_USE_ABILITY(ABILITY_10_TALON_TROT) || CAN_USE_TRANSFORMATION(TRANSFORM_2_TERMITE)),
        CHECK(RC_MM_NOTE_INSIDE_TICKERS_TOWER_1, 			CAN_USE_TRANSFORMATION(TRANSFORM_2_TERMITE)),
        CHECK(RC_MM_NOTE_INSIDE_TICKERS_TOWER_2, 			CAN_USE_TRANSFORMATION(TRANSFORM_2_TERMITE)),
        CHECK(RC_MM_NOTE_INSIDE_TICKERS_TOWER_3, 			CAN_USE_TRANSFORMATION(TRANSFORM_2_TERMITE)),
        CHECK(RC_MM_NOTE_INSIDE_TICKERS_TOWER_4, 			CAN_USE_TRANSFORMATION(TRANSFORM_2_TERMITE)),
        CHECK(RC_MM_NOTE_INSIDE_TICKERS_TOWER_5, 			CAN_USE_TRANSFORMATION(TRANSFORM_2_TERMITE)),
        CHECK(RC_MM_NOTE_INSIDE_TICKERS_TOWER_6, 			CAN_USE_TRANSFORMATION(TRANSFORM_2_TERMITE)),
    },
    .connections = {
        CONNECTION(RR_MUMBOS_MOUNTAIN, true),
        CONNECTION(RR_MUMBOS_MOUNTAIN_TICKERS_TOWER_TOP, CAN_USE_TRANSFORMATION(TRANSFORM_2_TERMITE)),
    },
};
Regions[RR_MUMBOS_MOUNTAIN_INTERIOR_MUMBOS_SKULL] = RandoRegion{ .regionName = "Mumbo's Mountain", .levelId = LEVEL_1_MUMBOS_MOUNTAIN,
    .checks = {
        CHECK(RC_MM_NOTE_INSIDE_MUMBOS_SKULL_1, 			true),
        CHECK(RC_MM_NOTE_INSIDE_MUMBOS_SKULL_2, 			true),
        CHECK(RC_MM_NOTE_INSIDE_MUMBOS_SKULL_3, 			true),
        CHECK(RC_MM_NOTE_INSIDE_MUMBOS_SKULL_4, 			true),
    },
    .connections = {
        CONNECTION(RR_MUMBOS_MOUNTAIN, true),
    },
};
Regions[RR_MUMBOS_MOUNTAIN_TICKERS_TOWER_TOP] = RandoRegion{ .regionName = "Mumbo's Mountain", .levelId = LEVEL_1_MUMBOS_MOUNTAIN,
    .checks = {
        CHECK(RC_MM_JIGGY_TICKERS_TOWER, 					true),
    },
    .connections = {
        CONNECTION(RR_MUMBOS_MOUNTAIN, true),
        CONNECTION(RR_MUMBOS_MOUNTAIN_INTERIOR_TICKERS_TOWER, true),
    },
};


    }, {});
// clang-format on