#include "src/port/ShipInit.hpp"
#include "src/port/Rando/Logic/Logic.h"

using namespace Rando::Logic;

// clang-format off
static RegisterShipInitFunc initFunc([]() {
    Regions[RR_GRUNTILDAS_LAIR_LOBBY] = RandoRegion{ .regionName = "Gruntilda's Lair Lobby", .levelId = LEVEL_6_LAIR,
        .checks = {
        // TODO: Events for each Witch Switch
		    CHECK(RC_GL_JIGGY_LOBBY, true),
            CHECK(RC_GL_JIGGY_WITCH_SWITCH_BUBBLEGLOOP_SWAMP, true),
            CHECK(RC_GL_JIGGY_WITCH_SWITCH_CLANKERS_CAVERN, true),
            CHECK(RC_GL_JIGGY_WITCH_SWITCH_CLICK_CLOCK_WOOD, true),
            CHECK(RC_GL_JIGGY_WITCH_SWITCH_FREEZEEZY_PEAK, true),
            CHECK(RC_GL_JIGGY_WITCH_SWITCH_GOBIS_VALLEY, true),
            CHECK(RC_GL_JIGGY_WITCH_SWITCH_MAD_MONSTER_MANSION, true),
            CHECK(RC_GL_JIGGY_WITCH_SWITCH_MUMBOS_MOUNTAIN, true),
            CHECK(RC_GL_JIGGY_WITCH_SWITCH_RUSTY_BUCKET_BAY, true),
            CHECK(RC_GL_JIGGY_WITCH_SWITCH_TREASURE_TROVE_COVE, true),
		},
        .connections = {
            // CONNECTION(RR_BUBBLEGLOOP_SWAMP, CAN_UNLOCK_WORLD(LEVEL_4_BUBBLEGLOOP_SWAMP)),
            // CONNECTION(RR_CLANKERS_CAVERN, CAN_UNLOCK_WORLD(LEVEL_3_CLANKERS_CAVERN)),
            // CONNECTION(RR_CLICK_CLOCK_WOOD, CAN_UNLOCK_WORLD(LEVEL_8_CLICK_CLOCK_WOOD)),
            // CONNECTION(RR_FREEZEEZY_PEAK, CAN_UNLOCK_WORLD(LEVEL_5_FREEZEEZY_PEAK)),
            CONNECTION(RR_GOBIS_VALLEY_ENTRANCE,    CAN_UNLOCK_WORLD(LEVEL_7_GOBIS_VALLEY)),
            // CONNECTION(RR_MAD_MONSTER_MANSION, CAN_UNLOCK_WORLD(LEVEL_A_MAD_MONSTER_MANSION)),
            CONNECTION(RR_MUMBOS_MOUNTAIN,          CAN_UNLOCK_WORLD(LEVEL_1_MUMBOS_MOUNTAIN)),
            CONNECTION(RR_RUSTY_BUCKET_BAY,         CAN_UNLOCK_WORLD(LEVEL_9_RUSTY_BUCKET_BAY)),
            CONNECTION(RR_TREASURE_TROVE_COVE,      CAN_UNLOCK_WORLD(LEVEL_2_TREASURE_TROVE_COVE)),
        },
    };
	
}, {});
// clang-format on