1fe1632098865f639e22c11b9a81ee8f29c75d7a:
  name: Banjo Kazooie (USA (Rev0))
  path: assets/yaml/us/rev0
  config:
    gbi: F3DEX_BK64
    sort: OFFSET
    logging: ERROR
    textures: ADDITIONAL_DEFINES
    output:
      binary: bk.o2r
      code: src/assets
      headers: include/assets
      modding: src/assets

ded6ee166e740ad1bc810fd678a84b48e245ab80:
  name: Banjo Kazooie (USA (Rev1))
  path: assets/yaml/us/rev1
  config:
    gbi: F3DEX
    sort: OFFSET
    logging: ERROR
    textures: ADDITIONAL_DEFINES
    output:
      binary: bk.o2r
      code: src/assets
      headers: include/assets
      modding: src/assets
