# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BUILD_SOURCE_DIRS "C:/claude/bk-wiiu/Lighthouse;C:/claude/bk-wiiu/Lighthouse/build-wiiu")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "YOUR NAME")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/Users/eduar/AppData/Local/Microsoft/WinGet/Packages/BrechtSanders.WinLibs.POSIX.UCRT_Microsoft.Winget.Source_8wekyb3d8bbwe/mingw64/share/cmake-4.4/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "Lighthouse built using CMake")
set(CPACK_GENERATOR "ZIP")
set(CPACK_INNOSETUP_ARCHITECTURE "x86")
set(CPACK_INSTALL_CMAKE_PROJECTS "C:/claude/bk-wiiu/Lighthouse/build-wiiu;Lighthouse;ALL;/")
set(CPACK_INSTALL_PREFIX "C:/devkitPro/portlibs/wiiu")
set(CPACK_MODULE_PATH "C:/devkitPro/cmake;C:/claude/bk-wiiu/Lighthouse/cmake/modules/")
set(CPACK_NSIS_DISPLAY_NAME "Lighthouse")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "\$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "Lighthouse")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "C:/devkitPro/devkitPPC/bin/powerpc-eabi-objcopy.exe")
set(CPACK_OBJDUMP_EXECUTABLE "C:/devkitPro/devkitPPC/bin/powerpc-eabi-objdump.exe")
set(CPACK_OUTPUT_CONFIG_FILE "C:/claude/bk-wiiu/Lighthouse/build-wiiu/CPackConfig.cmake")
set(CPACK_OUTPUT_FILE_PREFIX "C:/claude/bk-wiiu/Lighthouse/_packages")
set(CPACK_PACKAGE_CONTACT "YOUR@E-MAIL.net")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Users/eduar/AppData/Local/Microsoft/WinGet/Packages/BrechtSanders.WinLibs.POSIX.UCRT_Microsoft.Winget.Source_8wekyb3d8bbwe/mingw64/share/cmake-4.4/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Simple C++ application")
set(CPACK_PACKAGE_FILE_NAME "Lighthouse-1.1.0-CafeOS")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Lighthouse")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Lighthouse")
set(CPACK_PACKAGE_NAME "Lighthouse")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Some Company")
set(CPACK_PACKAGE_VERSION "1.1.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PROJECT_CONFIG_FILE "C:/claude/bk-wiiu/Lighthouse/cmake/configure-packaging.cmake")
set(CPACK_READELF_EXECUTABLE "C:/devkitPro/devkitPPC/bin/powerpc-eabi-readelf.exe")
set(CPACK_RESOURCE_FILE_LICENSE "C:/claude/bk-wiiu/Lighthouse/LICENSE.md")
set(CPACK_RESOURCE_FILE_README "C:/claude/bk-wiiu/Lighthouse/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "C:/Users/eduar/AppData/Local/Microsoft/WinGet/Packages/BrechtSanders.WinLibs.POSIX.UCRT_Microsoft.Winget.Source_8wekyb3d8bbwe/mingw64/share/cmake-4.4/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/claude/bk-wiiu/Lighthouse/build-wiiu/CPackSourceConfig.cmake")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_SYSTEM_NAME "CafeOS")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "CafeOS")
set(CPACK_VERBATIM_VARIABLES "YES")
set(CPACK_WIX_SIZEOF_VOID_P "4")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/claude/bk-wiiu/Lighthouse/build-wiiu/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
